#!/usr/bin/env bash
# AgroMart — Live Prices MERGE: keeps YOUR LivePrice.jsx (upgraded), removes duplicates.
# Adds: live API data, trend arrows, role CTAs, visual weight flip.
# Run from ~/Documents/AgroMart:  bash apply_lp_merge.sh
set -euo pipefail
[ -d backend/src ] || { echo "ERROR: run from ~/Documents/AgroMart"; exit 1; }
say(){ echo "  $*"; }

echo "==> [1/5] Replacing frontend/src/pages/LivePrice.jsx with merged version..."
echo 'aW1wb3J0IFJlYWN0LCB7IHVzZVN0YXRlLCB1c2VFZmZlY3QgfSBmcm9tICdyZWFjdCc7CmltcG9ydCB7IExpbmsgfSBmcm9tICdyZWFjdC1yb3V0ZXItZG9tJzsKaW1wb3J0IHsgdXNlTGFuZyB9IGZyb20gJy4uL2NvbnRleHQvTGFuZ0NvbnRleHQuanN4JzsKaW1wb3J0IHsgZ2V0TGl2ZVByaWNlcyB9IGZyb20gJy4uL2FwaS9wcmljZXMuYXBpLmpzJzsKCmNvbnN0IHRvQm5OdW0gPSAobnVtKSA9PiB7CiAgICBpZiAobnVtID09IG51bGwgfHwgbnVtID09PSAnJykgcmV0dXJuICcnOwogICAgY29uc3QgYm5OdW1zID0gWyfgp6YnLCAn4KenJywgJ+CnqCcsICfgp6knLCAn4KeqJywgJ+CnqycsICfgp6wnLCAn4KetJywgJ+CnricsICfgp68nXTsKICAgIHJldHVybiBTdHJpbmcobnVtKS5yZXBsYWNlKC9bMC05XS9nLCAoZGlnaXQpID0+IGJuTnVtc1tkaWdpdF0pOwp9OwoKLy8gRmFsbGJhY2sgc2VlZHMg4oCUIHVzZWQgb25seSBpZiB0aGUgQVBJIGlzIG9mZmxpbmUuIFNhbWUgc2V0ICsgc2hhcGUgYXMgdGhlCi8vIGxpdmUgQVBJIHJldHVybnMgKGNyb3BfbmFtZSBpbiBCZW5nYWxpIG1hdGNoZXMgbWFya2V0X3ByaWNlcyBzZWVkKS4KY29uc3Qgc2VlZENyb3BzID0gWwogICAgeyBjcm9wX25hbWU6ICfgppXgpr7gpoHgpprgpr7gpq7gprDgpr/gpponLCBjYXRlZ29yeV9uYW1lOiAnbHBfc3BpY2VzJywgICAgIGJhemFyX3JhdGU6IDE2MCwgYWdyb21hcnRfbWluOiAxNDAsIGFncm9tYXJ0X21heDogMTQwLCBhZ3JvbWFydF9hdmc6IDE0MCwgdHJlbmQ6ICdzdGFibGUnLCB0cmVuZF9wY3Q6IDAsIGltYWdlczogWycvY3JvcHMva2FjaGFtb3JpY2guanBnJ10sIGJlc3RfY3JvcF9pZDogbnVsbCwgdW5pdDogJ2tnJyB9LAogICAgeyBjcm9wX25hbWU6ICfgpqzgp4fgppfgp4HgpqgnLCAgICAgIGNhdGVnb3J5X25hbWU6ICdscF92ZWdldGFibGVzJywgYmF6YXJfcmF0ZTogNzAsICBhZ3JvbWFydF9taW46IDU4LCAgYWdyb21hcnRfbWF4OiA1OCwgIGFncm9tYXJ0X2F2ZzogNTgsICB0cmVuZDogJ3N0YWJsZScsIHRyZW5kX3BjdDogMCwgaW1hZ2VzOiBbJy9jcm9wcy9iZWd1bi5qcGcnXSwgICAgICAgYmVzdF9jcm9wX2lkOiBudWxsLCB1bml0OiAna2cnIH0sCiAgICB7IGNyb3BfbmFtZTogJ+CmsuCmvuCmiScsICAgICAgICBjYXRlZ29yeV9uYW1lOiAnbHBfdmVnZXRhYmxlcycsIGJhemFyX3JhdGU6IDYwLCAgYWdyb21hcnRfbWluOiA1MCwgIGFncm9tYXJ0X21heDogNTAsICBhZ3JvbWFydF9hdmc6IDUwLCAgdHJlbmQ6ICdzdGFibGUnLCB0cmVuZF9wY3Q6IDAsIGltYWdlczogWycvY3JvcHMvbGF1LmpwZyddLCAgICAgICAgIGJlc3RfY3JvcF9pZDogbnVsbCwgdW5pdDogJ3BpZWNlJyB9LAogICAgeyBjcm9wX25hbWU6ICfgpobgprLgp4EnLCAgICAgICAgY2F0ZWdvcnlfbmFtZTogJ2xwX3ZlZ2V0YWJsZXMnLCBiYXphcl9yYXRlOiA0MCwgIGFncm9tYXJ0X21pbjogMzIsICBhZ3JvbWFydF9tYXg6IDMyLCAgYWdyb21hcnRfYXZnOiAzMiwgIHRyZW5kOiAnc3RhYmxlJywgdHJlbmRfcGN0OiAwLCBpbWFnZXM6IFsnL2Nyb3BzL2FsdS5qcGcnXSwgICAgICAgICBiZXN0X2Nyb3BfaWQ6IG51bGwsIHVuaXQ6ICdrZycgfSwKICAgIHsgY3JvcF9uYW1lOiAn4Kaf4Kau4KeH4Kaf4KeLJywgICAgICBjYXRlZ29yeV9uYW1lOiAnbHBfdmVnZXRhYmxlcycsIGJhemFyX3JhdGU6IDg1LCAgYWdyb21hcnRfbWluOiA3MCwgIGFncm9tYXJ0X21heDogNzAsICBhZ3JvbWFydF9hdmc6IDcwLCAgdHJlbmQ6ICdzdGFibGUnLCB0cmVuZF9wY3Q6IDAsIGltYWdlczogWycvY3JvcHMvdG9tYXRvLmpwZyddLCAgICAgIGJlc3RfY3JvcF9pZDogbnVsbCwgdW5pdDogJ2tnJyB9LAogICAgeyBjcm9wX25hbWU6ICfgpqrgp4fgpoHgpq/gprzgpr7gppwnLCAgICBjYXRlZ29yeV9uYW1lOiAnbHBfc3BpY2VzJywgICAgIGJhemFyX3JhdGU6IDEwMCwgYWdyb21hcnRfbWluOiA4OCwgIGFncm9tYXJ0X21heDogODgsICBhZ3JvbWFydF9hdmc6IDg4LCAgdHJlbmQ6ICdzdGFibGUnLCB0cmVuZF9wY3Q6IDAsIGltYWdlczogWycvY3JvcHMvcGV5YWouanBnJ10sICAgICAgIGJlc3RfY3JvcF9pZDogbnVsbCwgdW5pdDogJ2tnJyB9LAogICAgeyBjcm9wX25hbWU6ICfgprjgprDgpr/gprfgpr4nLCAgICAgIGNhdGVnb3J5X25hbWU6ICdscF9ncmFpbnMnLCAgICAgYmF6YXJfcmF0ZTogMTEwLCBhZ3JvbWFydF9taW46IDk1LCAgYWdyb21hcnRfbWF4OiA5NSwgIGFncm9tYXJ0X2F2ZzogOTUsICB0cmVuZDogJ3N0YWJsZScsIHRyZW5kX3BjdDogMCwgaW1hZ2VzOiBbJy9jcm9wcy9zaG9yaXNoYS5qcGcnXSwgICAgYmVzdF9jcm9wX2lkOiBudWxsLCB1bml0OiAna2cnIH0sCiAgICB7IGNyb3BfbmFtZTogJ+CmruCngeCmlyDgpqHgpr7gprInLCAgIGNhdGVnb3J5X25hbWU6ICdscF9ncmFpbnMnLCAgICAgYmF6YXJfcmF0ZTogMTMwLCBhZ3JvbWFydF9taW46IDExNSwgYWdyb21hcnRfbWF4OiAxMTUsIGFncm9tYXJ0X2F2ZzogMTE1LCB0cmVuZDogJ3N0YWJsZScsIHRyZW5kX3BjdDogMCwgaW1hZ2VzOiBbJy9jcm9wcy9tdWdkYWwuanBnJ10sICAgICAgYmVzdF9jcm9wX2lkOiBudWxsLCB1bml0OiAna2cnIH0sCiAgICB7IGNyb3BfbmFtZTogJ+CmruCmuOCngeCmsCDgpqHgpr7gprInLCAgY2F0ZWdvcnlfbmFtZTogJ2xwX2dyYWlucycsICAgICBiYXphcl9yYXRlOiAxNDAsIGFncm9tYXJ0X21pbjogMTI1LCBhZ3JvbWFydF9tYXg6IDEyNSwgYWdyb21hcnRfYXZnOiAxMjUsIHRyZW5kOiAnc3RhYmxlJywgdHJlbmRfcGN0OiAwLCBpbWFnZXM6IFsnL2Nyb3BzL21vc3VyZGFsLmpwZyddLCAgICBiZXN0X2Nyb3BfaWQ6IG51bGwsIHVuaXQ6ICdrZycgfSwKXTsKCi8vIE1hcCBCZW5nYWxpIGNhdGVnb3J5IG5hbWVzIChmcm9tIERCKSB0byB5b3VyIGV4aXN0aW5nIGkxOG4ga2V5cywgc28gdGhlCi8vIGNhdGVnb3J5IGNoaXAgYW5kIGRyb3Bkb3duIGZpbHRlciBjb250aW51ZSB0byB3b3JrIHdpdGggdHJhbnNsYXRpb25zLgpjb25zdCBDQVRfQllfQk4gPSB7ICfgprjgpqzgppzgpr8nOiAnbHBfdmVnZXRhYmxlcycsICfgpqbgpr7gpqjgpr7gprbgprjgp43gpq8nOiAnbHBfZ3JhaW5zJywgJ+CmoeCmvuCmsic6ICdscF9ncmFpbnMnLCAn4Kau4Ka44Kay4Ka+JzogJ2xwX3NwaWNlcycgfTsKY29uc3QgY2F0S2V5T2YgPSAocm93KSA9PiBDQVRfQllfQk5bcm93LmNhdGVnb3J5X25hbWVdIHx8IHJvdy5jYXRlZ29yeV9uYW1lIHx8ICdscF92ZWdldGFibGVzJzsKCmNvbnN0IExpdmVQcmljZSA9ICgpID0+IHsKICAgIGNvbnN0IHsgdCwgbGFuZyB9ID0gdXNlTGFuZygpOwogICAgY29uc3QgW2Nyb3BzLCBzZXRDcm9wc10gPSB1c2VTdGF0ZShzZWVkQ3JvcHMpOwogICAgY29uc3QgW3NlYXJjaCwgc2V0U2VhcmNoXSA9IHVzZVN0YXRlKCcnKTsKICAgIGNvbnN0IFtjYXRlZ29yeSwgc2V0Q2F0ZWdvcnldID0gdXNlU3RhdGUoJycpOwogICAgY29uc3QgW3VzZXJSb2xlLCBzZXRVc2VyUm9sZV0gPSB1c2VTdGF0ZSgnYnV5ZXInKTsKCiAgICAvLyBGZXRjaCBsaXZlIGRhdGEgb24gbW91bnQgQU5EIHdoZW4gcm9sZSBjaGFuZ2VzIChzZXJ2ZXItc2lkZSBzb3J0IGRpZmZlcnMpCiAgICB1c2VFZmZlY3QoKCkgPT4gewogICAgICAgIGxldCBhbGl2ZSA9IHRydWU7CiAgICAgICAgZ2V0TGl2ZVByaWNlcyh7IHJvbGU6IHVzZXJSb2xlIH0pCiAgICAgICAgICAgIC50aGVuKChkYXRhKSA9PiB7CiAgICAgICAgICAgICAgICBpZiAoIWFsaXZlKSByZXR1cm47CiAgICAgICAgICAgICAgICBpZiAoZGF0YSAmJiBBcnJheS5pc0FycmF5KGRhdGEucHJpY2VzKSAmJiBkYXRhLnByaWNlcy5sZW5ndGggPiAwKSB7CiAgICAgICAgICAgICAgICAgICAgc2V0Q3JvcHMoZGF0YS5wcmljZXMpOwogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9KQogICAgICAgICAgICAuY2F0Y2goKCkgPT4gY29uc29sZS5sb2coJy9hcGkvcHJpY2VzIG9mZmxpbmUsIHNob3dpbmcgc2VlZHMnKSk7CiAgICAgICAgcmV0dXJuICgpID0+IHsgYWxpdmUgPSBmYWxzZTsgfTsKICAgIH0sIFt1c2VyUm9sZV0pOwoKICAgIGNvbnN0IGZpbHRlcmVkQ3JvcHMgPSBjcm9wcy5maWx0ZXIoKGMpID0+IHsKICAgICAgICBjb25zdCBjcm9wTmFtZSA9IChjLmNyb3BfbmFtZSB8fCAnJykudG9Mb3dlckNhc2UoKTsKICAgICAgICBjb25zdCBtYXRjaGVzU2VhcmNoID0gY3JvcE5hbWUuaW5jbHVkZXMoc2VhcmNoLnRvTG93ZXJDYXNlKCkpOwogICAgICAgIGNvbnN0IG1hdGNoZXNDYXQgPSBjYXRlZ29yeSA/IGNhdEtleU9mKGMpID09PSBjYXRlZ29yeSA6IHRydWU7CiAgICAgICAgcmV0dXJuIG1hdGNoZXNTZWFyY2ggJiYgbWF0Y2hlc0NhdDsKICAgIH0pOwoKICAgIHJldHVybiAoCiAgICAgICAgPGRpdiBzdHlsZT17eyBiYWNrZ3JvdW5kOiAnI2YwZjdlZScsIG1pbkhlaWdodDogJzEwMHZoJywgcGFkZGluZ0JvdHRvbTogJzY0cHgnIH19PgoKICAgICAgICAgICAgey8qIEhlYWRlciBCYW5uZXIgKi99CiAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgYmFja2dyb3VuZDogJyMxZTVlMmYnLCBwYWRkaW5nOiAnNDBweCAxNnB4IDYwcHgnLCB0ZXh0QWxpZ246ICdjZW50ZXInLCBjb2xvcjogJyNmZmYnIH19PgogICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9e3sgYmFja2dyb3VuZDogJ3JnYmEoMjU1LCAyNTUsIDI1NSwgMC4yKScsIHBhZGRpbmc6ICc2cHggMTZweCcsIGJvcmRlclJhZGl1czogJzIwcHgnLCBmb250U2l6ZTogJzEzcHgnLCBmb250V2VpZ2h0OiAnNTAwJywgZGlzcGxheTogJ2lubGluZS1mbGV4JywgYWxpZ25JdGVtczogJ2NlbnRlcicsIGdhcDogJzZweCcgfX0+CiAgICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9e3sgaGVpZ2h0OiAnOHB4Jywgd2lkdGg6ICc4cHgnLCBiYWNrZ3JvdW5kQ29sb3I6ICcjNGNhZjUwJywgYm9yZGVyUmFkaXVzOiAnNTAlJywgZGlzcGxheTogJ2lubGluZS1ibG9jaycgfX0+PC9zcGFuPgogICAgICAgICAgICAgICAgICAgIHt0KCdscF9iYWRnZScpfQogICAgICAgICAgICAgICAgPC9zcGFuPgoKICAgICAgICAgICAgICAgIDxoMSBzdHlsZT17eyBmb250U2l6ZTogJzI4cHgnLCBmb250V2VpZ2h0OiAnODAwJywgbWFyZ2luVG9wOiAnMTZweCcsIG1hcmdpbkJvdHRvbTogJzIwcHgnLCB0ZXh0QWxpZ246ICdjZW50ZXInIH19PgogICAgICAgICAgICAgICAgICAgIHt1c2VyUm9sZSA9PT0gJ2J1eWVyJyA/IHQoJ2xwX2J1eWVyVGl0bGUnKSA6IHQoJ2xwX2Zhcm1lclRpdGxlJyl9CiAgICAgICAgICAgICAgICA8L2gxPgoKICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZGlzcGxheTogJ2lubGluZS1mbGV4JywgYmFja2dyb3VuZDogJ3JnYmEoMCwgMCwgMCwgMC4yKScsIHBhZGRpbmc6ICc0cHgnLCBib3JkZXJSYWRpdXM6ICczMHB4JyB9fT4KICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIG9uQ2xpY2s9eygpID0+IHNldFVzZXJSb2xlKCdidXllcicpfSBzdHlsZT17cm9sZUJ0blN0eWxlKHVzZXJSb2xlID09PSAnYnV5ZXInKX0+e3QoJ2xwX2J1eWVyQnRuJyl9PC9idXR0b24+CiAgICAgICAgICAgICAgICAgICAgPGJ1dHRvbiBvbkNsaWNrPXsoKSA9PiBzZXRVc2VyUm9sZSgnZmFybWVyJyl9IHN0eWxlPXtyb2xlQnRuU3R5bGUodXNlclJvbGUgPT09ICdmYXJtZXInKX0+e3QoJ2xwX2Zhcm1lckJ0bicpfTwvYnV0dG9uPgogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAgey8qIFNlYXJjaCArIGZpbHRlciAqL30KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImNvbnRhaW5lciIgc3R5bGU9e3sgbWF4V2lkdGg6ICcxMTAwcHgnLCBtYXJnaW46ICctMzBweCBhdXRvIDAnLCBwYWRkaW5nOiAnMCAxNnB4JywgcG9zaXRpb246ICdyZWxhdGl2ZScsIHpJbmRleDogMTAgfX0+CiAgICAgICAgICAgICAgICA8ZGl2IHN0eWxlPXt7IGJhY2tncm91bmQ6ICcjZmZmJywgcGFkZGluZzogJzE2cHgnLCBib3JkZXJSYWRpdXM6ICcxMnB4JywgZGlzcGxheTogJ2ZsZXgnLCBnYXA6ICcxMnB4JywgbWFyZ2luQm90dG9tOiAnMjRweCcsIGJveFNoYWRvdzogJzAgNHB4IDEycHggcmdiYSgwLDAsMCwwLjA4KScgfX0+CiAgICAgICAgICAgICAgICAgICAgPGlucHV0IHR5cGU9InRleHQiIHBsYWNlaG9sZGVyPXt0KCdscF9zZWFyY2hQbGFjZWhvbGRlcicpfSB2YWx1ZT17c2VhcmNofSBvbkNoYW5nZT17KGUpID0+IHNldFNlYXJjaChlLnRhcmdldC52YWx1ZSl9CiAgICAgICAgICAgICAgICAgICAgICAgIHN0eWxlPXt7IGZsZXg6IDEsIHBhZGRpbmc6ICcxMHB4IDE0cHgnLCBib3JkZXI6ICcxcHggc29saWQgI2UwZTBlMCcsIGJvcmRlclJhZGl1czogJzhweCcsIG91dGxpbmU6ICdub25lJyB9fSAvPgogICAgICAgICAgICAgICAgICAgIDxzZWxlY3QgdmFsdWU9e2NhdGVnb3J5fSBvbkNoYW5nZT17KGUpID0+IHNldENhdGVnb3J5KGUudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgICAgICAgICAgICAgICAgc3R5bGU9e3sgcGFkZGluZzogJzEwcHggMTRweCcsIGJvcmRlcjogJzFweCBzb2xpZCAjZTBlMGUwJywgYm9yZGVyUmFkaXVzOiAnOHB4Jywgb3V0bGluZTogJ25vbmUnLCBiYWNrZ3JvdW5kOiAnI2ZmZicgfX0+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IiI+e3QoJ2xwX2FsbENhdCcpfTwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJscF9ncmFpbnMiPnt0KCdscF9ncmFpbnMnKX08L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0ibHBfdmVnZXRhYmxlcyI+e3QoJ2xwX3ZlZ2V0YWJsZXMnKX08L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0ibHBfc3BpY2VzIj57dCgnbHBfc3BpY2VzJyl9PC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgICB7LyogQ2FyZHMgKi99CiAgICAgICAgICAgICAgICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdncmlkJywgZ3JpZFRlbXBsYXRlQ29sdW1uczogJ3JlcGVhdChhdXRvLWZpbGwsIG1pbm1heCgyODBweCwgMWZyKSknLCBnYXA6ICcxNnB4JyB9fT4KICAgICAgICAgICAgICAgICAgICB7ZmlsdGVyZWRDcm9wcy5tYXAoKGMpID0+ICgKICAgICAgICAgICAgICAgICAgICAgICAgPENyb3BDYXJkIGtleT17Yy5jcm9wX25hbWV9IGM9e2N9IHJvbGU9e3VzZXJSb2xlfSBsYW5nPXtsYW5nfSB0PXt0fSAvPgogICAgICAgICAgICAgICAgICAgICkpfQogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgKTsKfTsKCmNvbnN0IHJvbGVCdG5TdHlsZSA9IChhY3RpdmUpID0+ICh7CiAgICBwYWRkaW5nOiAnOHB4IDIwcHgnLCBib3JkZXJSYWRpdXM6ICcyNXB4JywgYm9yZGVyOiAnbm9uZScsCiAgICBiYWNrZ3JvdW5kOiBhY3RpdmUgPyAnI2ZmZicgOiAndHJhbnNwYXJlbnQnLAogICAgY29sb3I6IGFjdGl2ZSA/ICcjMWU1ZTJmJyA6ICcjZmZmJywKICAgIGZvbnRXZWlnaHQ6ICc3MDAnLCBjdXJzb3I6ICdwb2ludGVyJywgZm9udFNpemU6ICcxNHB4JywgdHJhbnNpdGlvbjogJ2FsbCAwLjNzIGVhc2UnLAp9KTsKCmZ1bmN0aW9uIENyb3BDYXJkKHsgYywgcm9sZSwgbGFuZywgdCB9KSB7CiAgICBjb25zdCBpbWcgPSBBcnJheS5pc0FycmF5KGMuaW1hZ2VzKSA/IGMuaW1hZ2VzWzBdIDogYy5pbWFnZXM7CiAgICBjb25zdCBiYXphciA9IG51bShjLmJhemFyX3JhdGUpOwogICAgY29uc3QgYW1NaW4gPSBudW0oYy5hZ3JvbWFydF9taW4pOwogICAgY29uc3QgYW1NYXggPSBudW0oYy5hZ3JvbWFydF9tYXgpOwogICAgY29uc3QgYW1BdmcgPSBudW0oYy5hZ3JvbWFydF9hdmcpOwogICAgY29uc3Qgc2F2aW5ncyA9IGJhemFyICE9IG51bGwgJiYgYW1NaW4gIT0gbnVsbCA/IE1hdGgubWF4KDAsIGJhemFyIC0gYW1NaW4pIDogbnVsbDsKICAgIGNvbnN0IGdhcCA9IGJhemFyICE9IG51bGwgJiYgYW1NYXggIT0gbnVsbCA/IE1hdGgubWF4KDAsIGJhemFyIC0gYW1NYXgpIDogbnVsbDsKCiAgICByZXR1cm4gKAogICAgICAgIDxkaXYgc3R5bGU9e3sgYmFja2dyb3VuZDogJyNmZmYnLCBwYWRkaW5nOiAnMTZweCcsIGJvcmRlclJhZGl1czogJzE2cHgnLCBib3JkZXI6ICcxcHggc29saWQgI2UwZTBlMCcsIGJveFNoYWRvdzogJzAgNHB4IDEycHggcmdiYSgwLDAsMCwwLjAzKScsIGRpc3BsYXk6ICdmbGV4JywgZmxleERpcmVjdGlvbjogJ2NvbHVtbicgfX0+CiAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgd2lkdGg6ICcxMDAlJywgaGVpZ2h0OiAnMTQwcHgnLCBib3JkZXJSYWRpdXM6ICcxMnB4Jywgb3ZlcmZsb3c6ICdoaWRkZW4nLCBtYXJnaW5Cb3R0b206ICcxMnB4JywgYmFja2dyb3VuZDogJyNmNWY1ZjUnLCBwb3NpdGlvbjogJ3JlbGF0aXZlJyB9fT4KICAgICAgICAgICAgICAgIHtpbWcgPyAoCiAgICAgICAgICAgICAgICAgICAgPGltZyBzcmM9e2ltZ30gYWx0PXtjLmNyb3BfbmFtZX0gc3R5bGU9e3sgd2lkdGg6ICcxMDAlJywgaGVpZ2h0OiAnMTAwJScsIG9iamVjdEZpdDogJ2NvdmVyJyB9fSAvPgogICAgICAgICAgICAgICAgKSA6ICgKICAgICAgICAgICAgICAgICAgICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdncmlkJywgcGxhY2VJdGVtczogJ2NlbnRlcicsIGhlaWdodDogJzEwMCUnLCBmb250U2l6ZTogJzQ4cHgnIH19PvCfjL48L2Rpdj4KICAgICAgICAgICAgICAgICl9CiAgICAgICAgICAgICAgICB7LyogVHJlbmQgY2hpcCDigJQgdG9wLXJpZ2h0IG9mIGltYWdlICovfQogICAgICAgICAgICAgICAgPFRyZW5kQ2hpcCB0cmVuZD17Yy50cmVuZH0gcGN0PXtjLnRyZW5kX3BjdH0gbGFuZz17bGFuZ30gdD17dH0gLz4KICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgPGgzIHN0eWxlPXt7IG1hcmdpbjogMCwgZm9udFNpemU6ICcxNnB4JywgZm9udFdlaWdodDogJzcwMCcgfX0+e2MuY3JvcF9uYW1lfTwvaDM+CiAgICAgICAgICAgICAgICA8c21hbGwgc3R5bGU9e3sgY29sb3I6ICcjNjY2JyB9fT57dChjYXRLZXlPZihjKSl9PC9zbWFsbD4KICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICB7LyogUHJpY2VzIOKAlCBkaWZmZXJlbnQgdmlzdWFsIHdlaWdodCBwZXIgcm9sZSAqL30KICAgICAgICAgICAgPGRpdiBzdHlsZT17eyBtYXJnaW5Ub3A6ICcxMnB4JywgZGlzcGxheTogJ2ZsZXgnLCBqdXN0aWZ5Q29udGVudDogJ3NwYWNlLWJldHdlZW4nLCBhbGlnbkl0ZW1zOiAnZmxleC1lbmQnLCBmbGV4OiAxIH19PgogICAgICAgICAgICAgICAge3JvbGUgPT09ICdidXllcicgPyAoCiAgICAgICAgICAgICAgICAgICAgPGRpdj4KICAgICAgICAgICAgICAgICAgICAgICAgPHNtYWxsIHN0eWxlPXt7IGNvbG9yOiAnIzY2NicgfX0+e3QoJ2xwX2Fncm9QcmljZScpfTwvc21hbGw+CiAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZm9udFNpemU6ICcyMHB4JywgZm9udFdlaWdodDogJzgwMCcsIGNvbG9yOiAnIzJlN2QzMicgfX0+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICDgp7Mge2xhbmcgPT09ICdibicgPyB0b0JuTnVtKGFtTWluID8/ICfigJQnKSA6IChhbU1pbiA/PyAn4oCUJyl9IC97Yy51bml0ID09PSAncGllY2UnID8gdCgnbHBfcGVyUGllY2UnKSA6IHQoJ2xwX3BlcktnJyl9CiAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICA8ZGl2IHN0eWxlPXt7IGZvbnRTaXplOiAnMTJweCcsIHRleHREZWNvcmF0aW9uOiAnbGluZS10aHJvdWdoJywgY29sb3I6ICcjOTk5JyB9fT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIHt0KCdscF9tYXJrZXRQcmljZScpfTog4KezIHtsYW5nID09PSAnYm4nID8gdG9Cbk51bShiYXphciA/PyAn4oCUJykgOiAoYmF6YXIgPz8gJ+KAlCcpfQogICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICkgOiAoCiAgICAgICAgICAgICAgICAgICAgPGRpdj4KICAgICAgICAgICAgICAgICAgICAgICAgPHNtYWxsIHN0eWxlPXt7IGNvbG9yOiAnIzY2NicgfX0+e3QoJ2xwX21hcmtldFByaWNlJyl9PC9zbWFsbD4KICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBzdHlsZT17eyBmb250U2l6ZTogJzIwcHgnLCBmb250V2VpZ2h0OiAnODAwJywgY29sb3I6ICcjMWU1ZTJmJyB9fT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIOCnsyB7bGFuZyA9PT0gJ2JuJyA/IHRvQm5OdW0oYmF6YXIgPz8gJ+KAlCcpIDogKGJhemFyID8/ICfigJQnKX0gL3tjLnVuaXQgPT09ICdwaWVjZScgPyB0KCdscF9wZXJQaWVjZScpIDogdCgnbHBfcGVyS2cnKX0KICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZm9udFNpemU6ICcxMnB4JywgY29sb3I6ICcjNjY2JyB9fT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIHt0KCdscF9vdGhlcnNDaGFyZ2UnKX06IOCnsyB7bGFuZyA9PT0gJ2JuJyA/IHRvQm5OdW0oYW1BdmcgIT0gbnVsbCA/IE1hdGgucm91bmQoYW1BdmcpIDogJ+KAlCcpIDogKGFtQXZnICE9IG51bGwgPyBNYXRoLnJvdW5kKGFtQXZnKSA6ICfigJQnKX0KICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICApfQoKICAgICAgICAgICAgICAgIHsvKiBTYXZpbmdzIC8gZ2FwIHBpbGwgKi99CiAgICAgICAgICAgICAgICB7cm9sZSA9PT0gJ2J1eWVyJyAmJiBzYXZpbmdzID4gMCAmJiAoCiAgICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9e3sgYmFja2dyb3VuZDogJyNlOGY1ZTknLCBjb2xvcjogJyMyZTdkMzInLCBwYWRkaW5nOiAnNHB4IDEwcHgnLCBib3JkZXJSYWRpdXM6ICcxMnB4JywgZm9udFNpemU6ICcxMnB4JywgZm9udFdlaWdodDogJzYwMCcsIHdoaXRlU3BhY2U6ICdub3dyYXAnIH19PgogICAgICAgICAgICAgICAgICAgICAgICDgp7Mge2xhbmcgPT09ICdibicgPyB0b0JuTnVtKHNhdmluZ3MpIDogc2F2aW5nc30ge3QoJ2xwX3NhdmluZ3MnKX0KICAgICAgICAgICAgICAgICAgICA8L3NwYW4+CiAgICAgICAgICAgICAgICApfQogICAgICAgICAgICAgICAge3JvbGUgPT09ICdmYXJtZXInICYmIGdhcCA+IDAgJiYgKAogICAgICAgICAgICAgICAgICAgIDxzcGFuIHN0eWxlPXt7IGJhY2tncm91bmQ6ICcjZmZmM2UwJywgY29sb3I6ICcjZTY1MTAwJywgcGFkZGluZzogJzRweCAxMHB4JywgYm9yZGVyUmFkaXVzOiAnMTJweCcsIGZvbnRTaXplOiAnMTJweCcsIGZvbnRXZWlnaHQ6ICc2MDAnLCB3aGl0ZVNwYWNlOiAnbm93cmFwJyB9fT4KICAgICAgICAgICAgICAgICAgICAgICAg4KezIHtsYW5nID09PSAnYm4nID8gdG9Cbk51bShnYXApIDogZ2FwfSB7dCgnbHBfZGlmZicpfQogICAgICAgICAgICAgICAgICAgIDwvc3Bhbj4KICAgICAgICAgICAgICAgICl9CiAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAgey8qIFJvbGUtc3BlY2lmaWMgQ1RBICovfQogICAgICAgICAgICA8ZGl2IHN0eWxlPXt7IG1hcmdpblRvcDogJzE0cHgnIH19PgogICAgICAgICAgICAgICAge3JvbGUgPT09ICdidXllcicgPyAoCiAgICAgICAgICAgICAgICAgICAgYy5iZXN0X2Nyb3BfaWQgPyAoCiAgICAgICAgICAgICAgICAgICAgICAgIDxMaW5rIHRvPXtgL21hcmtldHBsYWNlLyR7Yy5iZXN0X2Nyb3BfaWR9YH0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgc3R5bGU9e2N0YUJ0blN0eWxlKCcjMmU3ZDMyJyl9PgogICAgICAgICAgICAgICAgICAgICAgICAgICAge3QoJ2xwX29yZGVyTm93Jyl9IOKGkgogICAgICAgICAgICAgICAgICAgICAgICA8L0xpbms+CiAgICAgICAgICAgICAgICAgICAgKSA6ICgKICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9e3sgZGlzcGxheTogJ2Jsb2NrJywgdGV4dEFsaWduOiAnY2VudGVyJywgZm9udFNpemU6ICcxMnB4JywgY29sb3I6ICcjOTk5JyB9fT57dCgnbHBfbm9MaXN0aW5ncycpfTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICApIDogKAogICAgICAgICAgICAgICAgICAgIDxMaW5rIHRvPXtgL2Zhcm1lci9jcm9wcy9uZXc/Y3JvcD0ke2VuY29kZVVSSUNvbXBvbmVudChjLmNyb3BfbmFtZSl9YH0KICAgICAgICAgICAgICAgICAgICAgICAgICBzdHlsZT17Y3RhQnRuU3R5bGUoJyNlNjUxMDAnKX0+CiAgICAgICAgICAgICAgICAgICAgICAgIHt0KCdscF9saXN0Tm93Jyl9IOKGkgogICAgICAgICAgICAgICAgICAgIDwvTGluaz4KICAgICAgICAgICAgICAgICl9CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgKTsKfQoKY29uc3QgY3RhQnRuU3R5bGUgPSAoY29sb3IpID0+ICh7CiAgICBkaXNwbGF5OiAnYmxvY2snLCB3aWR0aDogJzEwMCUnLCB0ZXh0QWxpZ246ICdjZW50ZXInLAogICAgYmFja2dyb3VuZDogY29sb3IsIGNvbG9yOiAnI2ZmZicsCiAgICBwYWRkaW5nOiAnMTBweCAxNHB4JywgYm9yZGVyUmFkaXVzOiAnMTBweCcsIGJvcmRlcjogJ25vbmUnLAogICAgZm9udFdlaWdodDogJzcwMCcsIGZvbnRTaXplOiAnMTNweCcsIGN1cnNvcjogJ3BvaW50ZXInLAogICAgdGV4dERlY29yYXRpb246ICdub25lJywKfSk7CgpmdW5jdGlvbiBUcmVuZENoaXAoeyB0cmVuZCwgcGN0LCBsYW5nLCB0IH0pIHsKICAgIGNvbnN0IG1hcCA9IHsKICAgICAgICB1cDogICAgIHsgaWNvbjogJ+KGkScsIGJnOiAnI2ZmZWJlZScsIGNvbG9yOiAnI2M2MjgyOCcgfSwKICAgICAgICBkb3duOiAgIHsgaWNvbjogJ+KGkycsIGJnOiAnI2U4ZjVlOScsIGNvbG9yOiAnIzJlN2QzMicgfSwKICAgICAgICBzdGFibGU6IHsgaWNvbjogJ+KGkicsIGJnOiAnI2Y1ZjVmNScsIGNvbG9yOiAnIzY2NicgfSwKICAgIH07CiAgICBjb25zdCBjZmcgPSBtYXBbdHJlbmRdIHx8IG1hcC5zdGFibGU7CiAgICBjb25zdCBkaXNwbGF5UGN0ID0gcGN0ICE9IG51bGwgPyBNYXRoLmFicyhOdW1iZXIocGN0KSkgOiBudWxsOwogICAgcmV0dXJuICgKICAgICAgICA8c3BhbiBzdHlsZT17ewogICAgICAgICAgICBwb3NpdGlvbjogJ2Fic29sdXRlJywgdG9wOiAnOHB4JywgcmlnaHQ6ICc4cHgnLAogICAgICAgICAgICBiYWNrZ3JvdW5kOiBjZmcuYmcsIGNvbG9yOiBjZmcuY29sb3IsCiAgICAgICAgICAgIHBhZGRpbmc6ICczcHggOHB4JywgYm9yZGVyUmFkaXVzOiAnMTBweCcsCiAgICAgICAgICAgIGZvbnRTaXplOiAnMTFweCcsIGZvbnRXZWlnaHQ6ICc3MDAnLAogICAgICAgICAgICBkaXNwbGF5OiAnaW5saW5lLWZsZXgnLCBhbGlnbkl0ZW1zOiAnY2VudGVyJywgZ2FwOiAnM3B4JywKICAgICAgICB9fT4KICAgICAgICAgICAge2NmZy5pY29ufSB7ZGlzcGxheVBjdCAhPSBudWxsID8gYCR7bGFuZyA9PT0gJ2JuJyA/IHRvQm5OdW0oZGlzcGxheVBjdCkgOiBkaXNwbGF5UGN0fSVgIDogJyd9CiAgICAgICAgPC9zcGFuPgogICAgKTsKfQoKZnVuY3Rpb24gbnVtKHYpIHsKICAgIGlmICh2ID09IG51bGwgfHwgdiA9PT0gJycpIHJldHVybiBudWxsOwogICAgY29uc3QgbiA9IE51bWJlcih2KTsKICAgIHJldHVybiBOdW1iZXIuaXNGaW5pdGUobikgPyBuIDogbnVsbDsKfQoKZXhwb3J0IGRlZmF1bHQgTGl2ZVByaWNlOwo=' | base64 -d > frontend/src/pages/LivePrice.jsx && say 'wrote LivePrice.jsx'

echo "==> [2/5] Removing duplicate files (my old installer's + your dead backend route)..."
for f in frontend/src/pages/LivePrices.jsx \
         backend/src/routes/LivePrice.route.js; do
  if [ -f "$f" ]; then rm "$f" && say "deleted $f"; else say "$f already gone"; fi
done

echo "==> [3/5] Fixing frontend/src/App.jsx (remove duplicate route + import)..."
python3 - frontend/src/App.jsx << 'PY'
import sys,re
f=sys.argv[1]; s=open(f).read()
# remove the plural LivePrices import (mine)
s=re.sub(r"import LivePrices from '\./pages/LivePrices\.jsx';\n?", "", s)
# remove the plural LivePrices route
s=re.sub(r'\s*<Route path="/prices" element=\{<LivePrices\s*/>\}\s*/>\n?', "\n", s)
# ensure singular LivePrice route remains — collapse any accidental double newlines
s=re.sub(r'\n\n\n+', '\n\n', s)
open(f,'w').write(s)
print("  cleaned App.jsx")
PY

echo "==> [4/5] Adding i18n keys used by the upgraded LivePrice..."
python3 - frontend/src/i18n/strings.js << 'PY'
import sys
f=sys.argv[1]; s=open(f).read()

# Keys used by the ORIGINAL LivePrice.jsx (add if missing so nothing regresses)
BASE_BN = {
    'lp_badge': 'রিয়েল-টাইম আপডেট',
    'lp_buyerTitle': 'লাইভ মার্কেট প্রাইস',
    'lp_farmerTitle': 'আজকের বাজার নির্দেশিকা',
    'lp_buyerBtn': 'ক্রেতা দৃশ্য',
    'lp_farmerBtn': 'কৃষক দৃশ্য',
    'lp_searchPlaceholder': 'ফসলের নাম...',
    'lp_allCat': 'সব ক্যাটাগরি',
    'lp_grains': 'দানাশস্য',
    'lp_vegetables': 'সবজি',
    'lp_spices': 'মসলা',
    'lp_agroPrice': 'AgroMart মূল্য',
    'lp_marketPrice': 'বাজার দর',
    'lp_perKg': 'কেজি',
    'lp_perPiece': 'পিস',
    'lp_savings': 'সাশ্রয়',
    'lp_diff': 'পার্থক্য',
    # NEW keys added by the merger:
    'lp_othersCharge': 'অন্যরা চাচ্ছেন',
    'lp_orderNow': 'অর্ডার করুন',
    'lp_listNow': 'তালিকাভুক্ত করুন',
    'lp_noListings': 'কোনো তালিকা নেই',
}
BASE_EN = {
    'lp_badge': 'Real-time update',
    'lp_buyerTitle': 'Live Market Prices',
    'lp_farmerTitle': "Today's Market Guide",
    'lp_buyerBtn': 'Buyer View',
    'lp_farmerBtn': 'Farmer View',
    'lp_searchPlaceholder': 'Search crop...',
    'lp_allCat': 'All Categories',
    'lp_grains': 'Grains',
    'lp_vegetables': 'Vegetables',
    'lp_spices': 'Spices',
    'lp_agroPrice': 'AgroMart Price',
    'lp_marketPrice': 'Market Rate',
    'lp_perKg': 'kg',
    'lp_perPiece': 'piece',
    'lp_savings': 'Savings',
    'lp_diff': 'Difference',
    'lp_othersCharge': 'Others charge',
    'lp_orderNow': 'Order now',
    'lp_listNow': 'List this crop',
    'lp_noListings': 'No listings',
}

def insert_missing(text, block, entries):
    # find "  block: {" then find matching closing "  },"
    m = __import__('re').search(r'(\b' + block + r'\s*:\s*\{)', text)
    if not m: return text, 0
    start = m.end()
    # find the matching '}' balancing braces
    depth = 1; i = start
    while i < len(text) and depth > 0:
        if text[i] == '{': depth += 1
        elif text[i] == '}': depth -= 1
        i += 1
    close = i - 1  # position of the '}'
    body = text[start:close]
    added = 0
    lines = []
    for k, v in entries.items():
        if f"{k}:" in body or f"'{k}'" in body or f'"{k}"' in body:
            continue
        # escape single quotes in value
        vv = v.replace("'", "\\'")
        lines.append(f"    {k}: '{vv}',")
        added += 1
    if not lines: return text, 0
    insert = ("\n" if not body.rstrip().endswith(',') and body.strip() else "") + "\n".join(lines) + "\n"
    return text[:close] + insert + text[close:], added

s, addA = insert_missing(s, 'bn', BASE_BN)
s, addB = insert_missing(s, 'en', BASE_EN)
open(f,'w').write(s)
print(f"  added {addA} bn keys, {addB} en keys (existing keys skipped)")
PY

echo "==> [5/5] Done."
echo ""
echo "════ Merge complete. Restart backend if not on nodemon, then: ════"
echo "  Open http://localhost:5173/prices"
echo ""
echo "You should see YOUR existing page (same look) BUT with:"
echo "  - Live data from /api/prices (real bazar rates + AgroMart listings)"
echo "  - Trend arrows on each image (↑ red / ↓ green / → grey with %)"
echo "  - Buyer CTA: 'Order now' -> jumps to that crop in marketplace"
echo "  - Farmer CTA: 'List this crop' -> jumps to crop form pre-filled"
echo "  - Farmer view: market rate is the BIG number (buyer view unchanged)"
